Reroll cost improvements
kabamgamer/dd2-strategy-hub pull request #41
Opened 2024-04-03 14:13 UTC by EllH

Improved reroll costs to have stack and single values and added cost to pity row, changed reroll tracker to use user data store and fixed a few small issues with it 
![image](https://github.com/kabamgamer/dd2-strategy-hub/assets/22617287/04862501-6d1f-496c-b2e7-a47dcaa64de6)

2024-04-03 15:21 UTC, EllH commented on src/stores/UserData.ts
> +            localStorage.setItem('rerollTracker', JSON.stringify(newRerollCount))
the new reroll format won't save if someone loads the page and doesn't change the reroll tracker without this

2024-04-03 21:17 UTC, kabamgamer commented
@EllH , thanks for another PR.
Could you please resolve merge conflicts, I made a few changes this morning.

2024-04-04 17:11 UTC, kabamgamer requested changes
Please fix merge conflicts

2024-04-05 19:02 UTC, EllH commented on src/components/sections/RerollCost.vue
> +              <td scope="row" v-for="calculateCosts in getCalculateCostForRerollCount(pitySystemLimit)" :key="calculateCosts">{{ calculateCosts }}</td>
@kabamgamer these keys aren't unique in a decent chunk of scenarios

2024-04-05 19:03 UTC, EllH commented
> Please fix merge conflicts

fixed

2024-04-05 19:04 UTC, EllH commented on src/components/sections/RerollCost.vue
> +              <td scope="row" v-for="calculateCosts in getCalculateCostForRerollCount(pitySystemLimit)" :key="calculateCosts">{{ calculateCosts }}</td>
easiest one to repo would be 0 as values

2024-04-05 19:49 UTC, EllH commented on src/components/sections/RerollCost.vue
> +              <td scope="row" v-for="calculateCosts in getCalculateCostForRerollCount(pitySystemLimit)" :key="calculateCosts">{{ calculateCosts }}</td>
I've fixed this in my latest commit, slightly changed how we build the table to having a list of "chaosTiers" with title, mote amount and gold amount, using row prefix + title

2024-04-05 20:02 UTC, kabamgamer approved these changes

2024-04-05 20:02 UTC, merged